version: '3.6'

services:
  app:
    image: github.com/dweidenfeld/app:dev
    build:
      context: .
      target: dev
    ports:
      - 50051:50051
    volumes:
      - .:/app
      - target:/app/target
    security_opt:
      - seccomp=unconfined

volumes:
  target:
